### ISSUE TITLE
How to test new changes

### ISSUE THREAD

**Issue by po10cio** [Salvatore-Giordano/CountryCodePicker#11]
Hi, well done here. I forked this project but I can not see the example project so that I can test the new changes that I am making.

**Comment by Salvatore-Giordano** [comment]
Hi thank you very much for the contribution.
I have not written yet any test, but that's in program. There is no example project, but just a code snippet in the readme.

Asap I'll fix this things, I'm really sorry

**Comment by po10cio** [comment]
How were you able to grab the screenshots. If you don't mind, I can fix it and give you a pull request.

**Comment by Salvatore-Giordano** [comment]
For the screenshots it was just a center with the widget as a child

**Comment by po10cio** [comment]
I have added an example project for testing the plugin, I will give you a pull request soon.
