### ISSUE TITLE
Flag Size

### ISSUE THREAD

**Issue by javad-vovin** [Salvatore-Giordano/CountryCodePicker#12]
Hi
After changing flags to png, the apk size increased by 9mb, can you reduce the size or at least change it back to use it from fonts?

**Comment by Salvatore-Giordano** [comment]
The problem is that on iOS and some Android phones the font may not work, but I can think on some solution. I'll let you know asap

**Comment by javad-vovin** [comment]
I think the solution is the width and height of flags, they are way too big, it can be done with 100*60. Thanks by the way
