### ISSUE TITLE
[Not Issue] Special Thanks.

### ISSUE THREAD

**Issue by dooboolab** [Salvatore-Giordano/CountryCodePicker#13]
This is not an issue but I just want to thank you for providing this plugin.
This worked great in my project in almost every case.
Thanks for your work and sharing.

It'd be best if this plugin provide localized strings for country name, but I know it is too much to provide them internally.

Thanks again.

**Comment by Salvatore-Giordano** [comment]
Thank you very much! This is really important to me.
I'll try to improve this plugin, I'm open to any request. 

About the localized strings I don't know if this would be worth it. By the way I'll think about it.

Fell free to suggest improvements, make pull requests or whatever 😃

**Comment by imtoori** [comment]
@hyochan I was just looking the closed issue list and I notice this one. I wanted to let you know that now the library implements localizations :)
