### ISSUE TITLE
can it show as other language？

### ISSUE THREAD

**Issue by linguitang** [Salvatore-Giordano/CountryCodePicker#14]

**Comment by Salvatore-Giordano** [comment]
At the moment no.
I'll work on that.

**Comment by linguitang** [comment]
[country_codes.txt](https://github.com/Salvatore-Giordano/CountryCodePicker/files/2486811/country_codes.txt)
I think replace country_codes.dart with the txt content will be better

**Comment by linguitang** [comment]
I have make a pull request。if the display info can be edit， it will be better。Because sometimes I just want to show country name int UI layer。

**Comment by kaiserleka** [comment]
How can I use list as English back instead of related languages own word

**Comment by shatanikmahanty** [comment]
I am sorry I didnot read the docs carefully.

@levent-kantaroglu Just add 

```
supportedLocales: [
            Locale("en"),
],
localizationsDelegates: [
            CountryLocalizations.delegate,
 ],
```

to material app to get all country names in English.
