### ISSUE TITLE
FYI: Flag emoji's now working on ios

### ISSUE THREAD

**Issue by mmcc007** [Salvatore-Giordano/CountryCodePicker#16]
It looks like the flag emoji issue on ios has been resolved see:
[flutter/issues/16960](https://github.com/flutter/flutter/issues/16960)
and 
[flutter/issues/9652](https://github.com/flutter/flutter/issues/9652)
It is currently in the master branch, should be in beta branch soon.

**Comment by Salvatore-Giordano** [comment]
Well, do you think it would be better to use the font instead of the images? 🤔

**Comment by mmcc007** [comment]
If flag fonts are rendering correctly on both android and ios, IMO the font is the better way to go. 

There may be come compatibility issues on older devices, who knows. I imagine that would be small chance.

**Comment by Salvatore-Giordano** [comment]
I think it's better to stick with the images as they have no compatibility issue
