### ISSUE TITLE
Unable to load flags

### ISSUE THREAD

**Issue by Djihanegh** [Salvatore-Giordano/CountryCodePicker#176]
When i added the package i got this exception:
Unable to load asset: packages/country_code_picker/flags/it.png

The flags can not be loaded, the package version is:   country_code_picker: ^2.0.2
What's the problem please ?

**Comment by Djihanegh** [comment]
Just stop and re run the app, the flags will be loaded

**Comment by FakharAlyas119** [comment]
i also try to stop the app and restart it again! still cant be able to load country flag
