### ISSUE TITLE
replacement of भारत

### ISSUE THREAD

**Issue by Pranav108** [Salvatore-Giordano/CountryCodePicker#182]
Country code +91 we can find the name `भारत`, but majority of Indian use English during typing .
Many of us Indians I understand both languages but everyone will prefer `India`  instead of  `भारत`.
So , changing name `भारत` to `India` will be more convenient for us.

**Comment by ZaidrazaNarsinh** [comment]
Add below lines to your material widget

supportedLocales: const [
          Locale("en"),   /// THIS IS FOR COUNTRY CODE PICKER
        ],
        localizationsDelegates: const [
          CountryLocalizations.delegate,  /// THIS IS FOR COUNTRY CODE PICKER
        ],
