### ISSUE TITLE
Can't show unicode flags on ios

### ISSUE THREAD

**Issue by Salvatore-Giordano** [Salvatore-Giordano/CountryCodePicker#3]

**Comment by mmcc007** [comment]
This looks like a known problem on ios for flutter: [flutter/issues/16960](https://github.com/flutter/flutter/issues/16960). Until it get's resolved, you could use images instead. For example, [these](http://www.famfamfam.com/lab/icons/flags/) images are public domain.

**Comment by lukepighetti** [comment]
@mmcc007 How are we supposed to insert images into a Text field?

**Comment by Salvatore-Giordano** [comment]
You can't, you should use a row and set the widgets as children

**Comment by lukepighetti** [comment]
That won't wrap though, right?

**Comment by mmcc007** [comment]
It looks like the flag emoji issue on ios has been resolved see:
[flutter/issues/16960](https://github.com/flutter/flutter/issues/16960)
and 
[flutter/issues/9652](https://github.com/flutter/flutter/issues/9652)
It is currently in the master branch, should be in beta branch soon.
