### ISSUE TITLE
How to change the background Color?

### ISSUE THREAD

**Issue by disburden** [Salvatore-Giordano/CountryCodePicker#9]
![2018-08-20 4 17 13](https://user-images.githubusercontent.com/1391188/44328621-97946500-a494-11e8-9ec2-68ad4afaecdf.png)

As title
tks!

**Comment by Salvatore-Giordano** [comment]
You want to change the color as the screenshot?

**Comment by disburden** [comment]
Not,the screenshot is current color,I want it to be white

**Comment by Salvatore-Giordano** [comment]
Ah ok. I'll fix that asap. It should be white 😅

**Comment by Salvatore-Giordano** [comment]
May I close it? @disburden

**Comment by disburden** [comment]
I have been busy recently. Sorry for not replying in time.
But what I see here is still blue? I have upgraded to version 1.0.2.
I think you should pick the color from the Theme. Can you tell me which one?

**Comment by disburden** [comment]
I solved the problem.
Just put it in the Theme and don't specify any colors,like this:
`child: Theme(
                        data: ThemeData(
//
                        ),
                        child: CountryCodePicker(
                            onChanged: (country) {
                                print(country.dialCode);
                                countryCode = country.dialCode;
                            },
                            textStyle: TextStyle(
                                    fontSize: 16.0
                            ),
                            // Initial selection and favorite can be one of code ('IT') OR dial_code('+39')
                            initialSelection: 'CN',
                            favorite: ['+86', 'china'],
                        ),
                    ),`
I don't know why, but it’s working well.

**Comment by Salvatore-Giordano** [comment]
Thank you @disburden I'll fix that as soon as possible.

**Comment by jason-nguessan** [comment]
This should be the fix :)

`  data: ThemeData(dialogTheme: DialogTheme(backgroundColor: Colors.white)`
